import { getBriefData } from '../adapter/BriefmsAdapter';

const toBriefCrud = async (action, client_id, brief_id, month, year) => {
  //   var navigate = useNavigate();
  let data = {};
  if ((action === "edit" || action === "view") && client_id && brief_id) {
    const responce = getBriefData(client_id, brief_id, month, year);
    await responce.then(function (result) {
      console.log(result);
      if (result.status === "Success") {
        let facebook = result.data.filter((el) => {
          return el.formtype === "facebook";
        });
        let google = result.data.filter((el) => {
          return el.formtype === "google";
        });

        let bing = result.data.filter((el) => {
          return el.formtype === "bing";
        });
        // console.log();
        let facebookdata = facebook[0]
          ? {
              fbusiness_name: facebook[0].business_name,
              fobjective: facebook[0].objective,
              fstart_date: facebook[0].start_date,
              fend_date: facebook[0].end_date,
              ftarget_markets: facebook[0].target_markets,
              fcustomer_type: facebook[0].customer_type,
              fkeywordtg: facebook[0].keywordtg,
              fdemogarphic_details_age: JSON.parse(
                facebook[0].demogarphic_details_age
              ),
              fdemogarphic_gender: JSON.parse(facebook[0].demogarphic_gender),
              fplacement: JSON.parse(facebook[0].placement),
              fdetailed_training: JSON.parse(facebook[0].detailed_training),
              flanguage: JSON.parse(facebook[0].language),
              faudience_size: facebook[0].audience_size,
              faudience_name: facebook[0].audience_name,
              fmatched_base: facebook[0].matched_base,
              fexclusion_audience_name: facebook[0].exclusion_audience_name,
              fdevice_targeting: JSON.parse(facebook[0].device_targeting),
              existingchannel_facebook: JSON.parse(
                facebook[0].existingchannel_facebook
              ),
              flast_month_learning: facebook[0].last_month_learning,
              fmt_monthly_spend_number: facebook[0].mt_monthly_spend_number,
              fmt_daily_spend_number: facebook[0].mt_daily_spend_number,
              fmt_cpop: facebook[0].mt_cpop,
              fmt_leads: facebook[0].mt_leads,
              fmt_appoitment_sale: facebook[0].mt_appoitment_sale,
              fmt_cpl: facebook[0].mt_cpl,
              fmt_mcp: facebook[0].mt_mcp,
              fmt_cpmcp: facebook[0].mt_cpmcp,
              fmt_cps: facebook[0].mt_cps,
              fmt_kyc: facebook[0].mt_kyc,
              fmt_cpkyc: facebook[0].mt_cpkyc,
              fmt_card: facebook[0].mt_card,
              fmt_cpcard: facebook[0].mt_cpcard,
              fmt_cpa: facebook[0].mt_cpa,
              fmt_cibil: facebook[0].mt_cibil,
              fmt_cpcibil: facebook[0].mt_cpcibil,
              fmt_coa: facebook[0].mt_coa,
              fmt_observation_period_number:
                facebook[0].mt_observation_period_number,
              fmt_cutoff_metrics_number: facebook[0].mt_cutoff_metrics_number,
              fmt_disbursal_volume: facebook[0].mt_disbursal_volume,
              fmt_onlinepurchase: facebook[0].mt_onlinepurchase,
              flmp_spend: facebook[0].lmp_spend,
              flmp_leads: facebook[0].lmp_leads,
              flmp_cpcibil: facebook[0].lmp_cpcibil,
              flmp_coa: facebook[0].lmp_coa,
              // flmp_cps: facebook[0].lmp_cps,
              flmp_appoitment_sale: facebook[0].lmp_appoitment_sale,
              flmp_cpl: facebook[0].lmp_cpl,
              flmp_mcp: facebook[0].lmp_mcp,
              flmp_cpmcp: facebook[0].lmp_cpmcp,
              flmp_cpa: facebook[0].lmp_cpa,
              flmp_kyc: facebook[0].lmp_kyc,
              flmp_cpkyc: facebook[0].lmp_cpkyc,
              flmp_card: facebook[0].lmp_card,
              flmp_cpcard: facebook[0].lmp_cpcard,
              flmp_onlinepurchase: facebook[0].lmp_onlinepurchase,
              flmp_cpl2: facebook[0].lmp_cpl2,
              flmp_cibil: facebook[0].lmp_cibil,
              flmp_disbursal_volume: facebook[0].lmp_disbursal_volume,
              fcreative_type: JSON.parse(facebook[0].creative_type),
              fany_recomendation: facebook[0].any_recomendation,
            }
          : {};
        let googledata = google[0]
          ? {
              gbusiness_name: google[0].business_name,
              gobjective: google[0].objective,
              gstart_date: google[0].start_date,
              gend_date: google[0].end_date,
              gtarget_markets: google[0].target_markets,
              gcustomer_type: google[0].customer_type,
              gkeywordtg: google[0].keywordtg,
              ginmarket: JSON.parse(google[0].inmarket),
              gdemogarphic_details_age: JSON.parse(
                google[0].demogarphic_details_age
              ),
              gdemogarphic_gender: JSON.parse(google[0].demogarphic_gender),
              gplacement: JSON.parse(google[0].placement),
              ghousehold_income: JSON.parse(google[0].household_income),
              glanguage: JSON.parse(google[0].language),
              gaudience_size: google[0].audience_size,
              gaudience_name: google[0].audience_name,
              gmatched_base: google[0].matched_base,
              gdevice_targeting: JSON.parse(google[0].device_targeting),
              gmt_monthly_spend_number: google[0].mt_monthly_spend_number,
              gmt_daily_spend_number: google[0].mt_daily_spend_number,
              gmt_kyc: google[0].mt_kyc,
              gmt_cpkyc: google[0].mt_cpkyc,

              glmp_appoitment_sale: google[0].lmp_appoitment_sale,
              glmp_daily_spend: google[0].lmp_daily_spend,
              glmp_cps: google[0].lmp_cps,
              glmp_leads: google[0].lmp_leads,
              glmp_cpl: google[0].lmp_cpl,
              glmp_mcp: google[0].lmp_mcp,
              glmp_cpmcp: google[0].lmp_cpmcp,
              glmp_kyc: google[0].lmp_kyc,
              glmp_cpkyc: google[0].lmp_cpkyc,
              glmp_card: google[0].lmp_card,
              glmp_cpcard: google[0].lmp_cpcard,
              glmp_coa: google[0].lmp_coa,
              glmp_spend: google[0].lmp_spend,
              glmp_cibil: google[0].lmp_cibil,
              glmp_cpcibil: google[0].lmp_cpcibil,
              glmp_disbursal_volume: google[0].lmp_disbursal_volume,
              glmp_observation_period_number:
                google[0].lmp_observation_period_number,
              glmp_cutoff_metrics_number: google[0].lmp_cutoff_metrics_number,
              gni_cibil: google[0].ni_cibil,
              gni_cpcibil: google[0].ni_cpcibil,
              gni_coa: google[0].ni_coa,
              gni_disbursal_volume: google[0].ni_disbursal_volume,
              existingchannel_google: JSON.parse(
                google[0].ni_existingchannel_google
              ),
              gni_creative_type: google[0].ni_creative_type,
              gni_any_recomendation: google[0].ni_any_recomendation,
              gni_cpl: google[0].ni_cpl,
              gni_mcp: google[0].ni_mcp,
              gni_cpmcp: google[0].ni_cpmcp,
              gni_cpa: google[0].ni_cpa,
              gni_kyc: google[0].ni_kyc,
              gni_cpkyc: google[0].ni_cpkyc,
              gni_card: google[0].ni_card,
              gni_cpcard: google[0].ni_cpcard,
            }
          : {};

        let bingdata = bing[0]
          ? {
              bbusiness_name: bing[0].business_name,
              bobjective: bing[0].objective,
              bstart_date: bing[0].start_date,
              bend_date: bing[0].end_date,
              btarget_markets: bing[0].target_markets,
              bcustomer_type: bing[0].customer_type,
              bkeywordtg: bing[0].keywordtg,
              binmarket: JSON.parse(bing[0].inmarket),
              bdemogarphic_details_age: JSON.parse(
                bing[0].demogarphic_details_age
              ),
              bdemogarphic_gender: JSON.parse(bing[0].demogarphic_gender),
              bplacement: JSON.parse(bing[0].placement),
              bhousehold_income: JSON.parse(bing[0].household_income),
              bdetailed_training: JSON.parse(bing[0].detailed_training),
              blanguage: JSON.parse(bing[0].language),
              baudience_size: bing[0].audience_size,
              baudience_name: bing[0].audience_name,
              bexclusion_audience_name: bing[0].exclusion_audience_name,
              bdevice_targeting: JSON.parse(bing[0].device_targeting),
              bmatched_base: bing[0].matched_base,
              bmt_monthly_spend_nmber: bing[0].mt_monthly_spend_nmber,
              blmp_leads: bing[0].lmp_leads,
              blmp_spend: bing[0].lmp_spend,
              blmp_mcp: bing[0].lmp_mcp,
              blmp_cibil: bing[0].lmp_cibil,
              blmp_cpibil: bing[0].lmp_cpibil,
              blmp_coa: bing[0].lmp_coa,
              blmp_disbursal_volume: bing[0].lmp_disbursal_volume,
              blmp_observation_period_nmber:
                bing[0].lmp_observation_period_nmber,
              blmp_cutoff_metrics_number: bing[0].lmp_cutoff_metrics_number,
              blmp_kyc: bing[0].lmp_kyc,
              blmp_cpkyc: bing[0].lmp_cpkyc,
              blmp_card: bing[0].lmp_card,
              blmp_ccard: bing[0].lmp_ccard,
              bcreative_type: [bing[0].creative_type],
              bany_recomendation: bing[0].any_recomendation,
            }
          : {};
        data = {
          ...facebookdata,
          ...googledata,
          ...bingdata,
        };
        console.log(data);
      } else {
      }
    });
  } else {
    data = {
      /* facebook  form filds */
      fbusiness_name: "",
      fobjective: "",
      fstart_date: "",
      fend_date: "",
      ftarget_markets: "",
      fcustomer_type: "",
      fkeywordtg: "",
      fdemogarphic_details_age: [],
      fdemogarphic_gender: [],
      fplacement: [],
      fdetailed_training: [],
      flanguage: [],
      faudience_size: "",
      faudience_name: "",
      fmatched_base: "",
      fexclusion_audience_name: "",
      fdevice_targeting: [],
      existingchannel_facebook: [],
      flast_month_learning: "",
      fmt_monthly_spend_number: "",
      fmt_daily_spend_number: "",
      fmt_cpop: "",
      fmt_leads: "",
      fmt_appoitment_sale: "",
      fmt_cpl: "",
      fmt_mcp: "",
      fmt_cpmcp: "",
      fmt_cps: "",
      fmt_kyc: "",
      fmt_cpkyc: "",
      fmt_card: "",
      fmt_cpcard: "",
      fmt_cpa: "",
      fmt_cibil: "",
      fmt_cpcibil: "",
      fmt_coa: "",
      fmt_observation_period_number: "",
      fmt_cutoff_metrics_number: "",
      fmt_disbursal_volume: "",
      fmt_onlinepurchase: "",
      flmp_spend: "",
      flmp_leads: "",
      flmp_cpcibil: "",
      flmp_coa: "",
      // flmp_cps: "",
      flmp_appoitment_sale: "",
      flmp_cpl: "",
      flmp_mcp: "",
      flmp_cpmcp: "",
      flmp_cpa: "",
      flmp_kyc: "",
      flmp_cpkyc: "",
      flmp_card: "",
      flmp_cpcard: "",
      flmp_onlinepurchase: "",
      flmp_cpl2: "",
      flmp_cibil: "",
      flmp_disbursal_volume: "",
      fexisting_channels: [],
      fcreative_type: [],
      fany_recomendation: "",
      /* google form filds */
      gbusiness_name: "",
      gobjective: "",
      gstart_date: "",
      gend_date: "",
      gtarget_markets: "",
      gcustomer_type: "",
      gkeywordtg: "",
      ginmarket: [],
      gdemogarphic_details_age: [],
      gdemogarphic_gender: [],
      gplacement: [],
      ghousehold_income: [],
      glanguage: [],
      gaudience_size: "",
      gaudience_name: "",
      gmatched_base: "",
      gdevice_targeting: [],
      gmt_monthly_spend_number: "",
      gmt_daily_spend_number: "",
      gmt_kyc: "",
      gmt_cpkyc: "",
      glmp_appoitment_sale: "",
      glmp_daily_spend: "",
      glmp_cps: "",
      glmp_leads: "",
      glmp_cpl: "",
      glmp_mcp: "",
      glmp_cpmcp: "",
      glmp_kyc: "",
      glmp_cpkyc: "",
      glmp_card: "",
      glmp_cpcard: "",
      glmp_coa: "",
      glmp_spend: "",
      glmp_cibil: "",
      glmp_cpcibil: "",
      glmp_disbursal_volume: "",
      glmp_observation_period_number: "",
      glmp_cutoff_metrics_number: "",
      gni_cibil: "",
      gni_cpcibil: "",
      gni_coa: "",
      gni_disbursal_volume: "",
      existingchannel_google: [],
      gni_creative_type: "",
      gni_any_recomendation: "",
      gni_cpl: "",
      gni_mcp: "",
      gni_cpmcp: "",
      gni_cpa: "",
      gni_kyc: "",
      gni_cpkyc: "",
      gni_card: "",
      gni_cpcard: "",
      // /* bing form filds */
      bbusiness_name: "",
      bobjective: "",
      bstart_date: "",
      bend_date: "",
      btarget_markets: "",
      bcustomer_type: "",
      bkeywordtg: "",
      binmarket: [],
      bdemogarphic_details_age: [],
      bdemogarphic_gender: [],
      bplacement: [],
      bhousehold_income: "",
      bdetailed_training: [],
      blanguage: [],
      baudience_size: "",
      baudience_name: "",
      bexclusion_audience_name: "",
      bdevice_targeting: [],
      bmatched_base: "",
      bmt_monthly_spend_number: "",
      blmp_leads: "",
      blmp_spend: "",
      blmp_mcp: "",
      blmp_cibil: "",
      blmp_cpcibil: "",
      blmp_coa: "",
      blmp_disbursal_volume: "",
      blmp_observation_period_number: "",
      blmp_cutoff_metrics_number: "",
      blmp_kyc: "",
      blmp_cpkyc: "",
      blmp_card: "",
      blmp_cpcard: "",
      bcreative_type: [],
      bany_recomendation: "",
    };
  }
  return {
    action: action,
    client_id: client_id,
    brief_id: brief_id,
    month: month,
    year: year,
    data: data,
  };
};

export default toBriefCrud;
